version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
      - image: circleci/mysql:5.7.22
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_PASSWORD: 'p'
        MYSQL_DATABASE: jpcp_dev

    working_directory: ~/repo

    steps:
      - checkout
      - run:
        name: install
        command: 'sudo npm install'
      - run:
        name: database-online
        command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
        name: database-setup
        command: 'mysql < src/migration/initial-create.sql'
      - run:
        name: database-test-seed
        command: 'mysql < src/migration/test-seed.sql'
      - run:
        name: database-migrate
        command: 'npm run migrate:up'
